/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("org.jetbrains.kotlin:kotlin-reflect:1.8.0-RC")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.0-RC")
    implementation("org.springframework.boot:spring-boot-starter-data-jpa:3.0.2")
    implementation("org.springframework.boot:spring-boot-starter-web:3.0.2")
    implementation("org.springframework.boot:spring-boot-starter-validation:3.0.2")
    implementation("com.h2database:h2:2.1.214")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.14.1")
    testImplementation("org.springframework.boot:spring-boot-starter-test:3.0.2")
    testImplementation("org.junit.jupiter:junit-jupiter:5.8.2")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.4.2")
}

tasks {
    test {
        useJUnitPlatform()
    }
}

group = "ygmd"
version = "1.0.0"
description = "TodoBackendKT"
java.sourceCompatibility = JavaVersion.VERSION_1_10

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
